senbox-org/snap-engine

beam-core/src/main/java/org/esa/beam/framework/datamodel/ProductData.java

update UTC(double mjd) constructor to handle negative microseconds

---

beam-core/src/main/java/org/esa/beam/dataio/dimap/EnviHeader.java

Fallback to toString when strict formatting with toWkt fails

---

snap-core/src/main/java/org/esa/snap/framework/dataop/resamp/BiCubicInterpolationResampling.java
snap-core/src/main/java/org/esa/snap/framework/dataop/resamp/BiSincInterpolationResampling.java
snap-core/src/main/java/org/esa/snap/framework/dataop/resamp/BilinearInterpolationResampling.java
snap-core/src/main/java/org/esa/snap/framework/dataop/resamp/CubicConvolutionResampling.java
snap-core/src/main/java/org/esa/snap/framework/dataop/resamp/NearestNeighbourResampling.java
snap-core/src/main/java/org/esa/snap/framework/dataop/resamp/Resampling.java
snap-core/src/test/java/org/esa/snap/framework/dataop/resamp/BiSincInterpolationResamplingTest.java
snap-core/src/test/java/org/esa/snap/framework/dataop/resamp/BicubicInterpolationResamplingTest.java
snap-core/src/test/java/org/esa/snap/framework/dataop/resamp/BilinearInterpolationResamplingTest.java
snap-core/src/test/java/org/esa/snap/framework/dataop/resamp/CubicConvolutionResamplingTest.java
snap-core/src/test/java/org/esa/snap/framework/dataop/resamp/NearestNeighbourResamplingTest.java

Added computeCornerBasedIndex with 'pixel' value at 0,0 instead of 0.5,0.5

modified to used computeCornerBasedIndex

---

snap-envisat-reader/src/main/java/org/esa/snap/dataio/envisat/EnvisatProductReaderPlugIn.java

This adds two new RGBImageProfiles for ATSR with a more "natural" look (i.e. vegetation is green, water is blue, snow/ice is cyan...)  It also changes the default profile selected to be the nadir view.

Update default ATSR RGBImageProfile

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/internal/OperatorContext.java

I need the progressMonitor to be able to indicate progress in StoredGraphOp.

Use progressMonitor in executeOperator.

---

snap-core/src/main/java/org/esa/snap/core/dataio/dimap/DimapProductHelpers.java

Related to: 
http://forum.step.esa.int/t/cant-open-safed-dim-files-in-snap-error-angle-is-too-high/4938 
and similar to: 
https://senbox.atlassian.net/projects/SIITBX/issues/SIITBX-252 
When the dimap reader creates the crsGeoCoding for every band, it is always using the bounds of the scene (usually this is 10980x10980 in a S2 image, with a spatial resolution of 10m). If these bounds are used with the angles bands which have a spatial resolution of 5000m the error is produced (in this bands the width and height is 22).

Use specific bounds for each band when creating CrsGeoCoding in dimap

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/Resample.java

If you agree, I will apply also this change to the branch 5.X

Make createInterpolatedMultiLevelImage public

---

snap-raster/src/main/java/org/esa/snap/raster/gpf/masks/CreateLandMaskOp.java

Please, see https://senbox.atlassian.net/projects/SNAP/issues/SNAP-814

Fix SNAP-814

---

snap-sta/src/main/java/org/esa/snap/core/gpf/operators/tooladapter/ToolAdapterOp.java

Fix the nullpointerException detected in the postprocessing of the sen2cor sta. If you agree, please also commit in 6.X branch

Fix NullPointerException

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/GenericNetCdfReaderPlugIn.java

please verify and merge into master ...

[SNAP-866] NetCdf files with extension '.nc.gz' are not read

---

snap-core/pom.xml

fix public package

---

snap-core/src/main/java/org/esa/snap/core/dataio/dimap/DimapProductHelpers.java

See https://senbox.atlassian.net/projects/SNAP/issues/SNAP-1082

Correct bandinfo reading when opening a DIMAP multisize product

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/ResamplingOp.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/beam/BeamInitialisationPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfGeocodingPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfInitialisationPart.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/GloballyShiftedDataTest.java

Fixed an issue where NetCDF4 file was written incorrectly in cases when "lat\lon" variables are 2-dimensional and presented in the source file.

Snap 1079 net cdf not readable

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfGeocodingPart.java

Fix for the case where for some Geocoding instances "lat/lon" band were not created properly. 
See https://senbox.atlassian.net/browse/SNAP-1088

ensure latVarName and lonVarName are assigned

---

snap-netcdf/pom.xml
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfBandPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/Constants.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfBandPartTest.java

Issue SNAP-917

---

snap-collocation/src/main/java/org/esa/snap/collocation/CollocateOp.java
snap-collocation/src/test/java/org/esa/snap/collocation/CollocateOpTest.java

See the newly added test. Before, you got a nullpointerexception, now you get an operatorexception.

Toniof improve error messages

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/DefaultNetCdfWriter.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfBandPart.java

NetCDF writer ensures that file has a proper filename extension.

---

ceres-ui/src/main/java/com/bc/ceres/swing/progress/ProgressMonitorSwingWorker.java
snap-core/src/main/java/org/esa/snap/core/datamodel/Product.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/GPF.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/graph/GraphProcessor.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/internal/OperatorContext.java

This pr contains some fixes to overcome issues discovered after integrating the redesigned doExecute-approach.

Toniof doexecute fixes

---

snap-binning/src/main/java/org/esa/snap/binning/Bin.java
snap-binning/src/main/java/org/esa/snap/binning/BinContext.java
snap-binning/src/main/java/org/esa/snap/binning/TemporalBin.java
snap-binning/src/main/java/org/esa/snap/binning/aggregators/AggregatorAverage.java
snap-binning/src/main/java/org/esa/snap/binning/aggregators/AggregatorAverageOutlierAware.java
snap-binning/src/main/java/org/esa/snap/binning/aggregators/AggregatorPercentile.java
snap-binning/src/test/java/org/esa/snap/binning/BinManagerTest.java
snap-binning/src/test/java/org/esa/snap/binning/TemporalBinTest.java
snap-binning/src/test/java/org/esa/snap/binning/aggregators/AggregatorTestUtils.java

Fixed bug in Binning module where the internal counter was not used correctly

resolve SNAP-1164 and SNAP-1165

---

snap-core/src/main/java/org/esa/snap/core/datamodel/GeoPos.java

SEADAS-001b: (Add format options to geopos)

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/WriteOp.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/common/WriteVirtualBandWithWriteOpTest.java

The test testWritingVirtualBand() in WriteVirtualBandWithWriteOpTest now is adapted to the WriteOp changes.

Write tile row

---

snap-core/src/main/java/org/esa/snap/core/image/BandOpImage.java
snap-core/src/test/java/org/esa/snap/core/image/BandOpImageTest.java
snap-core/src/test/java/org/esa/snap/core/image/BandOpImageTest_Static_PackageLocal.java
snap-envi-reader/src/main/java/org/esa/snap/dataio/envi/EnviProductReader.java

Snap 1182  fixed

---

snap-core/src/main/java/org/esa/snap/core/datamodel/Band.java

Fix raw storage size estimation in Band

Storage estimation

---

snap-pconvert/src/main/java/org/esa/snap/pconvert/PConvertMain.java

Added option "-B" or "--band-names" to select bands by name in pconvert

---

snap-core/src/test/java/org/esa/snap/core/util/io/FileUtilsTest_RelativeUri.java
snap-core/src/test/java/org/esa/snap/core/util/io/TreeCopierTest.java
snap-csv-dataio/src/test/java/org/esa/snap/csv/dataio/CsvFileTest.java
snap-csv-dataio/src/test/java/org/esa/snap/csv/dataio/reader/CsvProduct2x2Test.java
snap-csv-dataio/src/test/java/org/esa/snap/csv/dataio/reader/CsvProductReaderPlugInTest.java
snap-csv-dataio/src/test/java/org/esa/snap/csv/dataio/reader/CsvProductReaderTest.java
snap-csv-dataio/src/test/java/org/esa/snap/csv/dataio/writer/CsvProductWriterTest2.java
snap-dem/src/test/java/org/esa/snap/gpf/AddElevationOpTest.java
snap-geotiff/src/test/java/org/esa/snap/dataio/geotiff/GeoCodingTest.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/common/ProductSetReaderOpTest.java
snap-pixel-extraction/src/test/java/org/esa/snap/pixex/PixExOpTest.java
snap-raster/src/test/java/org/esa/snap/raster/gpf/texture/GLCMOp_IntegrationTest.java
snap-statistics/src/test/java/org/esa/snap/statistics/StatisticsOpTest.java
snap-statistics/src/test/java/org/esa/snap/statistics/TestUtil.java
snap-statistics/src/test/java/org/esa/snap/statistics/tools/StatisticsDatabaseTest.java
snap-statistics/src/test/java/org/esa/snap/statistics/tools/SummaryCSVToolTest.java
snap-watermask/src/test/java/org/esa/snap/watermask/util/ShapeFileRasterizerTest.java

Some fixes for unit tests on Windows when blank spaces in path

Test jenkins windows

---

README.md

Link pointed to The Ecological Society of America.

Fixed ESA web address

---

snap-binning/src/main/java/org/esa/snap/binning/aggregators/AggregatorAverageOutlierAware.java

Changed condition to skip values from smaller to smallerEqual.

---

snap-core/src/main/java/org/esa/snap/core/image/AbstractMatrixMosaicSubsetMultiLevelSource.java
snap-core/src/main/java/org/esa/snap/core/image/AbstractMosaicSubsetMultiLevelSource.java
snap-core/src/main/java/org/esa/snap/core/util/ImageUtils.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffMultiLevelSource.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffProductReader.java

The branch contains the changes to fix the exception when running the acceptance product reader tests.

Fix exception when creating the Mosaic image for GeoTiff MultiLevelSource

---

snap-bigtiff/src/main/java/org/esa/snap/dataio/bigtiff/BigGeoTiffProductWriter.java

I would like to change the default behaviour of the BigGeotiff Writer. The LZW compression should be enabled by default. I think this is safe to do, but would like to know your opinion

Using LZW compression by default for BigGeoTiff writing

---

snap-core/src/main/java/org/esa/snap/core/dataio/dimap/DimapHeaderWriter.java
snap-core/src/test/java/org/esa/snap/core/dataio/dimap/DimapHeaderWriterTest.java

Band_index was just not written.

[SNAP-1293] Band_Index tag is not written for BEAM-DIMAP when PixelGeoCoding is used for multiple bands

---

snap-product-library-v2/pom.xml
snap-remote-products-repository/pom.xml

like:
[ERROR] Project depends on packages not accessible at runtime in module org.esa.snap:ceres-jai:jar:8.0.0-SNAPSHOT

updated dependencies in order to remove dependencies errors

---

snap-classification/src/main/java/org/esa/snap/classification/gpf/BaseClassifier.java

This fix ensures that several of the gpt tests run.

handle classifier exceptions

---

snap-python/src/main/resources/snappy/snappyutil.py

Still getting a syntax error because of unbalanced parenthesis. 
Change from #146

fix #146 again

---

snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/AbstractLocalRepositoryFolderHelper.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/AddLocalRepositoryFolderHelper.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/ScanLocalRepositoryFolderHelper.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/model/LocalRepositoryProduct.java
snap-remote-products-repository/src/main/java/org/esa/snap/remote/products/repository/RepositoryProduct.java
snap-remote-products-repository/src/main/java/org/esa/snap/remote/products/repository/donwload/RemoteRepositoriesManager.java
snap-remote-products-repository/src/main/java/org/esa/snap/remote/products/repository/donwload/RemoteRepositoryProductImpl.java
snap-remote-products-repository/src/main/java/org/esa/snap/remote/products/repository/listener/ProgressListener.java

Product Library V2 - add timeline feature

Product library 28 05 2020

---

snap-core/src/main/java/org/esa/snap/core/dataio/AbstractProductReader.java
snap-core/src/main/java/org/esa/snap/core/dataio/dimap/DimapProductReader.java
snap-core/src/main/java/org/esa/snap/core/image/BandOpImage.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/internal/OperatorContext.java

… BandOpImage checks if the reader can be used to read higher level data

fix for read higher level data

---

snap-collocation/src/main/java/org/esa/snap/collocation/CollocateOp.java
snap-collocation/src/test/java/org/esa/snap/collocation/CollocateOpTest.java

… Subidentifiers like flag names will not be updated.

SNAP-662 Issue with renaming flags in expressions

---

snap-core/src/main/java/org/esa/snap/core/datamodel/TiePointGrid.java

Solves https://senbox.atlassian.net/browse/SNAP-1334

SNAP-1334: Creation of Tie-Point Grid Subsets can be slow

---

snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffImageReader.java

With this change the tiff from the zip works.
See the comment and my mail for more info.

Avoid MemoryCacheImageInputStream for tiff files

---

snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/inverse/PixelQuadTreeInverse.java
snap-core/src/test/java/org/esa/snap/core/dataio/geocoding/inverse/PixelQuadTreeInverseTest.java

see   "Consideration of the latitude when epsilon is included in the calculations.pdf" in
https://brockmannconsult.sharepoint.com/sites/snap/Freigegebene%20Dokumente/General/Consideration%20of%20the%20latitude%20when%20epsilon%20is%20included%20in%20the%20calculations.pdf

Consider latitude in epsilon calculation for logitude direction

---

snap-core/src/main/java/org/esa/snap/core/subset/GeometrySubsetRegion.java
snap-core/src/main/java/org/esa/snap/core/subset/PixelSubsetRegion.java
snap-core/src/main/java/org/esa/snap/core/util/GeoUtils.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/SubsetOp.java

Related to the snap-desktop PR
https://github.com/senbox-org/snap-desktop/pull/124

Snap-1301 Fix subset op for the small ROI

---

snap-core/src/main/java/org/esa/snap/core/util/math/IntervalPartition.java
snap-core/src/main/java/org/esa/snap/core/util/math/LookupTable.java
snap-core/src/test/java/org/esa/snap/core/util/math/IntervalPartitionTest.java
snap-core/src/test/java/org/esa/snap/core/util/math/LookupTableTest.java

This pull request enables lookup tables, which exhibit coordinate axis (dimensions) where the coordinate values are either strictly decreasing or strictly increasing.

Enable lookup tables with decreasing coordinate axis values

---

snap-virtual-file-system/pom.xml
snap-virtual-file-system/src/main/java/org/esa/snap/vfs/remote/AbstractRemoteFileSystem.java

Can we remove the dependency to jetbrains?
It is only used at on place and is not helping much.

remove jetbrains dependency

---

snap-core/src/main/java/org/esa/snap/core/dataio/dimap/DimapProductHelpers.java
snap-core/src/main/java/org/esa/snap/core/dataio/dimap/spi/BandMathsMaskPersistable.java
snap-core/src/main/java/org/esa/snap/core/dataio/dimap/spi/ConvolutionFilterBandPersistable.java
snap-core/src/main/java/org/esa/snap/core/dataio/dimap/spi/DimapPersistable.java
snap-core/src/main/java/org/esa/snap/core/dataio/dimap/spi/GeneralFilterBandPersistable.java
snap-core/src/main/java/org/esa/snap/core/dataio/dimap/spi/MaskPersistable.java
snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistable.java
snap-core/src/main/java/org/esa/snap/core/datamodel/ConvolutionFilterBand.java
snap-core/src/main/java/org/esa/snap/core/datamodel/RGBImageProfile.java
snap-core/src/test/java/org/esa/snap/core/dataio/dimap/spi/BandMathMaskPersistableTest.java
snap-core/src/test/java/org/esa/snap/core/dataio/dimap/spi/ConvolutionFilterBandPersistableTest.java
snap-core/src/test/java/org/esa/snap/core/dataio/dimap/spi/GeneralFilterBandPersistableTest.java
snap-core/src/test/java/org/esa/snap/core/dataio/dimap/spi/MaskPersistableTest.java
snap-core/src/test/java/org/esa/snap/core/dataio/dimap/spi/RangeTypeMaskPersistableTest.java
snap-core/src/test/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistableTest.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/beam/BeamBandPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/beam/BeamGeocodingPart.java

Could you please test if the subsetting still works for you use case and merge if you agree?
Thanks

remove regionRasterSize from DimapPersistable

---

snap-core/src/main/java/org/esa/snap/core/datamodel/RGBImageProfile.java
snap-core/src/test/java/org/esa/snap/core/datamodel/RGBImageProfileTest.java
snap-envisat-reader/src/main/java/org/esa/snap/dataio/envisat/EnvisatProductReaderPlugIn.java
snap-pconvert/src/main/java/org/esa/snap/pconvert/PConvertMain.java

Tom snap 520

---

snap-core/src/main/java/org/esa/snap/core/datamodel/ColorManipulationDefaults.java
snap-core/src/main/java/org/esa/snap/core/datamodel/ColorPaletteDef.java
snap-core/src/main/java/org/esa/snap/core/datamodel/ColorSchemeInfo.java
snap-core/src/main/java/org/esa/snap/core/datamodel/ImageInfo.java
snap-core/src/main/java/org/esa/snap/core/util/NamingConvention.java
snap-core/src/main/java/org/esa/snap/core/util/NamingConventionSnap.java
snap-core/src/main/java/org/esa/snap/core/util/ResourceInstaller.java
snap-core/src/main/java/org/esa/snap/core/util/math/Histogram.java
snap-core/src/main/java/org/esa/snap/core/util/math/LogLinearTransform.java

https://senbox.atlassian.net/browse/SNAP-1438
authored-by: Default Seadas User daniel.s.knowles@nasa.gov

[SNAP-1438] Improvement of Colour Manipulation Tool 

---

snap-collocation/src/main/java/org/esa/snap/collocation/CollocateOp.java

This is required for https://senbox.atlassian.net/browse/SITBX-730

add heading angle of slaves to metadata

---

snap-core/src/main/java/org/esa/snap/core/util/GeoUtils.java

Subset operator: computed spatial region are different for the same original resolution
https://senbox.atlassian.net/browse/SNAP-1461*

SNAP-1461 - fix spatial subset - FD

---

snap-dem/src/main/java/org/esa/snap/dem/gpf/AddElevationOp.java

The gpt test of the AddElevationTest_S2 doesn't no end.

Terminate AddElevation op during the gpt tests

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/SubsetOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/internal/RasterDataNodeValues.java

use tiepoint grids parameter in subset operator

Siitbx 357 fix tiepointgrid

---

snap-virtual-file-system/src/main/java/org/esa/snap/vfs/activator/VFSPlugInActivator.java

PR for issue:
https://senbox.atlassian.net/browse/SNAP-1470

[SNAP-1470] catch throwable

---

lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/OpenJP2Decoder.java
snap-arcbingrid-reader/pom.xml
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/SubsetOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/internal/RasterDataNodeValues.java
snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/JP2ProductReader.java
snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/internal/JP2TileOpImage.java

This evolution includes major updates on the products format with respect to the current baseline (PB 03.01; PSD version 14.6).
The S2 evolution include the update of the jp2 reader to manage the source with more 4 bands.

SIITBX 463 s2 evolution 8x

---

ceres-glayer/src/main/java/com/bc/ceres/glevel/support/AbstractMultiLevelSource.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/OpenJP2Decoder.java
snap-arcbingrid-reader/pom.xml
snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/JP2ProductReader.java
snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/internal/JP2TileOpImage.java

This evolution includes major updates on the products format with respect to the current baseline (PB 03.01; PSD version 14.6).
The S2 evolution include the update of the jp2 reader to manage the source with more 4 bands.

Siitbx 463 s2 evolution

---

snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/internal/JP2MosaicBandMatrixCell.java
snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/internal/JP2TileOpImage.java
snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/metadata/OpjDumpFile.java

Corrections for negative tile index errors noticed on old product S2A_USER_PRD_MSIL2A_PDMC_20160710T185720_R051_V20160710T105247_20160710T105247.SAFE

JP2 reader negative index error corrections

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfMetadataPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/nc/NFileWriteable.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/MetadataUtils.java

Metadata is now added into a group named "METADATA_GROUP".

[SNAP-1568] Metadata of product is not written to NetCDF-CF format

---

.gitlab-ci.yml
pom.xml

- Get compiled classes from Build stage
- Update Sonarqube config to set the path to compiled clases

Fix SonarQube config

---

.gitlab-ci.yml

Basic stages are :
- Build (all Maven commands)
- Test (SonarQube & security checks)
Status report to Github

[SCM-141] Add security Stage

---

.gitlab-ci.yml

- Add options to publish artifacts
- Update to-be-continuous template version

[SRM-74] Publish artifacts to Nexus

---

snap-znap/src/main/java/org/esa/snap/dataio/znap/ZnapProductReaderPlugIn.java
snap-znap/src/test/java/org/esa/snap/dataio/znap/ZnapProductReaderPlugInTest_getDecodeQualification.java

The related issue: https://senbox.atlassian.net/browse/SNAP-3479
The report in the forum:
https://forum.step.esa.int/t/snap-9-0-0-unexpected-exception-a-java-lang/39029

[SNAP-3479] Exception in decode qualification of ZnapProductReader

---

lib-openjpeg/pom.xml
snap-sta/pom.xml

If you are okay with the change, directly merge it and delete the branch, please.
Thanks

removed JNA version 5.5.0 and using instead 5.13.0 defined in snap-engine

---

lib-gdal/src/main/java/org/esa/snap/dataio/gdal/GDALVersion.java

Fix for bug on solution for [SNAP-3472](https://senbox.atlassian.net/browse/SNAP-3472).
[SNAP-3472]: https://senbox.atlassian.net/browse/SNAP-3472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3472_lib-gdal_26062023

---

lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/Band.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/ColorTable.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/Dataset.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/Driver.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/GCP.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/GDAL.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/GDALBase.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/GDALConst.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/GDALConstConstants.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/GDALReflection.java
lib-gdal/src/main/java/org/esa/snap/dataio/gdal/drivers/OSR.java

Reverts senbox-org/snap-engine#398

Revert "Revert "Replaced reflective calls to GDAL bindings with method handles""

---

snap-dem/src/main/java/org/esa/snap/dem/gpf/AddElevationOp.java
snap-dem/src/test/java/org/esa/snap/gpf/AddElevationOpTest.java

check for demName and demResamplingMethod 
add tests

SNAP-3576 check parameters are valid and catch Exceptions

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfGeocodingPart.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfGeocodingPartTest.java

Read geo-location data in file based tile size

improve reading performance

---

snap-gdal-reader/src/main/java/org/esa/snap/dataio/gdal/reader/GDALProductReader.java

SNAP-3630 if not overviews exists then create them
https://senbox.atlassian.net/browse/SNAP-3630

SNAP-3630 if not overviews exists then create them

---

snap-core/src/main/java/org/esa/snap/core/datamodel/Product.java
snap-core/src/test/java/org/esa/snap/core/datamodel/ProductTest.java

and added some tests, a bit of cleanup, too

resolved SNAP-1157

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/SubsetOp.java

Fix for [SNAP-3753](https://senbox.atlassian.net/browse/SNAP-3753).
[SNAP-3753]: https://senbox.atlassian.net/browse/SNAP-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3753_subsetOp

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfBandPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfGeocodingPart.java
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/ReaderUtils.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfGeocodingPartTest.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/util/ReaderUtilsTest.java

Now checks for scale and offset and applies accordingly.

resolves SNAP-3825

---

lib-gdal/src/main/java/org/esa/snap/dataio/gdal/GDALLoader.java
pom.xml
snap-core/src/main/java/eu/esa/snap/core/lib/NativeLibraryTools.java
snap-core/src/test/java/eu/esa/snap/core/lib/NativeLibraryToolsTest.java
snap-netcdf/pom.xml
snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/NetCdfActivator.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/GloballyShiftedDataTest.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/Nc4ReaderTest.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/metadata/profiles/beam/BeamTileSizeTest.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/metadata/profiles/cf/CfTileSizeTest.java
snap-netcdf/src/test/java/org/esa/snap/dataio/netcdf/nc/MaxStringAttributeLengthTest.java
snap-znap/src/test/java/org/esa/snap/dataio/znap/ZnapProductWriteAndReadTest_allAvailableBinaryWriters.java

Added native library support for NetCDF

---

snap-core/src/main/java/org/esa/snap/core/datamodel/RasterDataNode.java
snap-engine-utilities/pom.xml
snap-engine-utilities/src/main/java/org/esa/snap/engine_utilities/gpf/OperatorUtils.java
snap-engine-utilities/src/main/java/org/esa/snap/engine_utilities/gpf/TileGeoreferencing.java
snap-engine-utilities/src/test/java/org/esa/snap/engine_utilities/gpf/TestOperatorUtils.java
snap-engine-utilities/src/test/java/org/esa/snap/engine_utilities/gpf/TileGeoreferencingTest.java
snap-raster/src/main/java/org/esa/snap/raster/gpf/masks/CreateLandMaskOp.java
snap-raster/src/main/java/org/esa/snap/raster/gpf/masks/TerrainMaskOp.java
snap-stac/pom.xml

Support bands with their own geocoding

Srm 147 wv

---

snap-gdal-reader/src/main/java/org/esa/snap/dataio/gdal/reader/GDALTileOpImage.java

Should avoid 
Caused by: java.lang.IllegalMonitorStateException
at java.base/java.lang.Object.wait(Native Method)
at org.esa.snap.dataio.gdal.reader.GDALTileOpImage$ImageReader.readRasterFromDataset(GDALTileOpImage.java:103)
at org.esa.snap.dataio.gdal.reader.GDALTileOpImage$ImageReader.read(GDALTileOpImage.java:93)

Using Thread.sleep instead of wait and not using a loop to retry reading.

---

lib-hdf/pom.xml

Fix for [SNAP-3902](https://senbox.atlassian.net/browse/SNAP-3902).
[SNAP-3902]: https://senbox.atlassian.net/browse/SNAP-3902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3902_lib-hdf_ecostress-reader_probav-reader

---

snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/DataAccess.java

Fix for [SNAP-3777](https://senbox.atlassian.net/browse/SNAP-3777).
[SNAP-3777]: https://senbox.atlassian.net/browse/SNAP-3777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3777_product_library

---

snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/preferences/RepositoriesCredentialsPersistence.java
snap-remote-products-repository/pom.xml
snap-remote-products-repository/src/test/java/org/esa/snap/remote/products/repository/RemoteRepositoriesManagerTest.java

Fix for [SNAP-3771](https://senbox.atlassian.net/browse/SNAP-3771); [SNAP-3772](https://senbox.atlassian.net/browse/SNAP-3772); [SNAP-3773](https://senbox.atlassian.net/browse/SNAP-3773); [SNAP-3774](https://senbox.atlassian.net/browse/SNAP-3774); [SNAP-3775](https://senbox.atlassian.net/browse/SNAP-3775)
[SNAP-3771]: https://senbox.atlassian.net/browse/SNAP-3771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAP-3772]: https://senbox.atlassian.net/browse/SNAP-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAP-3773]: https://senbox.atlassian.net/browse/SNAP-3773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAP-3774]: …

SNAP-3771_SNAP-3772_SNAP-3773_SNAP-3774_SNAP-3775_product_library

---

snap-core/src/main/java/org/esa/snap/core/datamodel/ColorPaletteDef.java
snap-core/src/test/java/org/esa/snap/core/datamodel/ColorPaletteDefTest.java
snap-core/src/test/resources/org/esa/snap/core/datamodel/AlosAV2_color_palette.cpd
snap-core/src/test/resources/org/esa/snap/core/datamodel/spectrum.cpd
snap-core/src/test/resources/org/esa/snap/core/datamodel/too_small_spectrum.cpd

resolves SNAP-3961 and SNAP-3962

added loading and storing of labels

---

ceres-core/src/main/java/com/bc/ceres/core/VirtualDir.java
snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/Quicklook.java
snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/QuicklookGenerator.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/DataAccess.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/LocalRepositoryFolderHelper.java

Fix for [SNAP-3947](https://senbox.atlassian.net/browse/SNAP-3947).
[SNAP-3947]: https://senbox.atlassian.net/browse/SNAP-3947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3947_product-library

---

snap-gdal-reader/src/main/java/org/esa/snap/dataio/gdal/reader/GDALProductReader.java

Fix for [SNAP-3975](https://senbox.atlassian.net/browse/SNAP-3975).
[SNAP-3975]: https://senbox.atlassian.net/browse/SNAP-3975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3975_gdal-reader-fix-for-rapideye_412x

---

snap-remote-products-repository/pom.xml
snap-remote-products-repository/src/main/java/org/esa/snap/remote/products/repository/download/RemoteRepositoriesManager.java
snap-remote-products-repository/src/test/java/org/esa/snap/remote/products/repository/RemoteRepositoriesManagerTest.java

Fix for [SNAP-4031](https://senbox.atlassian.net/browse/SNAP-4031).
[SNAP-4031]: https://senbox.atlassian.net/browse/SNAP-4031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-4031_snap-remote-products-repository

---

snap-remote-products-repository/pom.xml

Fix for [SNAP-3986](https://senbox.atlassian.net/browse/SNAP-3986).
[SNAP-3986]: https://senbox.atlassian.net/browse/SNAP-3986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3986_snap-remote-products-repository

---

snap-sta/src/main/java/org/esa/snap/core/gpf/descriptor/dependency/BundleInstaller.java
snap-sta/src/main/java/org/esa/snap/core/gpf/operators/tooladapter/ToolAdapterIO.java

Improved & fixed some aspects of the ToolsAdapter
@kraftek 
@dianaharosa 
@TomBlock This is needed for sen2water
Especially the commit "using long as download by counter totalRead".
Otherwise downloads can't be bigger than ~2GB

Toolsadapter improvements

---

snap-sta/src/main/java/org/esa/snap/core/gpf/operators/tooladapter/ToolAdapterIO.java

This is an addition to pull-request #555. This commit was unfortunately not pushed to the branch
@TomBlock 
@kraftek

root path replacement must also use the token

---

ceres-jai/src/test/java/com/bc/ceres/jai/operator/ReinterpretDescriptorTest.java
snap-core/src/main/java/org/esa/snap/core/datamodel/RasterDataNode.java
snap-core/src/test/java/org/esa/snap/core/datamodel/RasterDataNodeTest.java

I might have encounter some issues with the geophysical data type of RasterDataNode.
I added some tests and some of the results indicate issues. I have marked them with a to-do and a comment.
Maybe you can review it and fix them if they are actual issues

Possible issues with GeophysicalDataType

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/util/NetcdfFileOpener.java

Fix for [SNAP-3997](https://senbox.atlassian.net/browse/SNAP-3997).
[SNAP-3997]: https://senbox.atlassian.net/browse/SNAP-3997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3997_snap-netcdf_13x

---

ceres-core/src/main/java/com/bc/ceres/core/VirtualDir.java
snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/Quicklook.java
snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/QuicklookGenerator.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/DataAccess.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/LocalRepositoryFolderHelper.java

Fix for [SNAP-3947](https://senbox.atlassian.net/browse/SNAP-3947) and links to [SNAP-3997](https://senbox.atlassian.net/browse/SNAP-3997).
[SNAP-3947]: https://senbox.atlassian.net/browse/SNAP-3947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAP-3997]: https://senbox.atlassian.net/browse/SNAP-3997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3997_product-library_13x

---

ceres-core/src/main/java/com/bc/ceres/core/VirtualDir.java
snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/Quicklook.java
snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/QuicklookGenerator.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/DataAccess.java
snap-product-library-v2/src/main/java/org/esa/snap/product/library/v2/database/LocalRepositoryFolderHelper.java

Fix for [SNAP-3947](https://senbox.atlassian.net/browse/SNAP-3947) and links to [SNAP-3997](https://senbox.atlassian.net/browse/SNAP-3997).
[SNAP-3947]: https://senbox.atlassian.net/browse/SNAP-3947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAP-3997]: https://senbox.atlassian.net/browse/SNAP-3997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3997_product-library
