snap-core/src/main/java/org/esa/snap/util/geotiff/GeoTIFFCodes.java
snap-core/src/main/java/org/esa/snap/util/geotiff/codes/geokey.properties
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/TiffTagToMetadataConverter.java

GDAL ver >= 1.9 writes GeoTIFF files with a GeogTOWGS84GeoKey geokey set in its metadata, which is unrecognised by SNAP's GeoTIFF reader, resulting in a NullPointerException and the image failing to open.
Unknown geokeys should probably just be ignored. I added the GeogTOWGS84GeoKey to the geokey registry, too.

Ignore unknown GeoTIFF geokeys instead of failing

---

snap-core/src/main/java/org/esa/snap/util/io/SnapFileFilter.java

Different readers can return the same file filter (for example the different Sentinel2 MSI L1C readers specific to each UTM zone).
This commit allows for different reader plugin to return the same file filter.
The list of file filters appearing in the Open Product dialog then shows only unique file filters.

Ensure file filters do not appear several times

---

snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/TiffFileInfo.java

With some GeoTiffs getGeoAsciiParamValues return zero length asciiValues

fix assignment when asciiValues may be zero length

---

snap-python/src/main/java/org/esa/snap/python/PyBridge.java

Make figuring out what went wrong with snappyutil.py a bit easier.
(snappyutil.py configuration failed for me because the SNAP installer does not include a Python 3.5 wheel for jpy right now.)

Suggest checking snappyutil.log if snappyutil.py fails

---

snap-core/src/main/java/org/esa/snap/core/util/ProductUtils.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/ReadOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/graph/NodeContext.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/graph/GraphCallSequenceTest.java

This allows the Graph Builder to reuse Products already opened in the ProductManager and in particular to use a modified product rather than reread from disk where the modification may not exist.
Also, copyVirtualBands is a useful function which was in OperatorUtils and now is in ProductUtils. It allows a virtual band to be copied from a source product to a target product without triggering any processing and still remaining a virtual band.

Reuse products

---

snap-core/src/main/java/org/esa/snap/core/datamodel/RGBImageProfile.java

With this modification, it is checked also that the expressions for R, G and B have the same size.

Check raster size in bands R, G and B

---

ceres-glayer/src/main/java/com/bc/ceres/glevel/support/DefaultMultiLevelImage.java

In Sentinel-2, we know the tilelayout before creating the multilevel image. If we use this new constructor the performance is improved because we do not need to create the level 0 image until the user open a specific band.

Added new constructor with layout for DefaultMultiLevelImage

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/ReadOp.java

If there are masks "bandMathType", before copying them in copyProductNodes, it checks if the bands are available. So if the bands have not been copied before the masks are not going to be added.

CopyProductNodes after copying bands.

---

snap-core/src/main/java/org/esa/snap/core/dataio/dimap/spi/RasterDataNodePersistable.java

Please, could you take a look at this? I was having some problems of georeference when writing a mask and I think that the location of the "ImageToModelTransform" value has changed inside the element (now it is inside an attribute).

fix setImageToModelTransform in RasterDataNodePersistable

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/WriteOp.java

There is a problem when trying to write some bands of a multisize product. If the selected bands have all the same size but this size is different from the scene size, the writeEntireTileRows will be used but there is a conflict with the tile size (the target preferred tile size will be the same that in the source product but this one is different from the size calculated (in determineTileSize) for the writableBands).

Set target product preferred tile size equals to determined tile size.

---

ceres-core/src/main/java/com/bc/ceres/core/PrintWriterConciseProgressMonitor.java
ceres-core/src/main/java/com/bc/ceres/core/PrintWriterProgressMonitor.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/main/DefaultCommandLineContext.java

Adds progress monitor for gpt operator and graph processing
Added PrintWriterConciseProgressMonitor to avoid being too verbal on the output
It adds minor ticks to show some progress for heavy processing jobs:
....10%....20%....

[SNAP-650] add progress indicator to gpt

---

snap-raster/src/main/java/org/esa/snap/raster/gpf/masks/CreateLandMaskOp.java
snap-raster/src/test/java/org/esa/snap/raster/gpf/masks/CreateLandMaskOpTest.java

@jun--lu can check this please?
I hope it breaks nothing else

[SNAP-817] Land-Sea-Mask fails when source has a pixel based geo-coding

---

snap-raster/src/main/java/org/esa/snap/raster/gpf/ConvertDataTypeOp.java

If a product scales the data like Landsat-8, the convertDataType will process the wrong data values unless scaling is applied first.
Test: Convert a Landsat-8 product from UInt16 to UInt8

scaling should be applied first if needed

---

snap-core/src/main/java/org/esa/snap/core/datamodel/quicklooks/QuicklookGenerator.java

allow access to reusable functionality

make QuicklookGenerator public

---

snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffProductReader.java

image description may exist but be empty. This should fall back on inputFile name.

product name field could be empty

---

snap-ndvi/src/main/java/org/esa/snap/ndvi/NdviOp.java
snap-ndvi/src/test/java/org/esa/snap/ndvi/NdviOpTest.java

The NDVI ignores the nodatavalue.
Zero may not be the best nodatavalue but an actual zero in the data should be rare and most export file formats don't handle non-zero nodatavalues well.

apply nodatavalue

---

snap-netcdf/src/main/java/org/esa/snap/dataio/netcdf/DefaultNetCdfWriter.java

I called writeRasterData method of Band. but DefaultNetCdfWriter throw NullPointerException.
I think DefaultNetCdfWriter need to add writeable null check logic.
thank you.

Add a null check to DefaultNetCdfWriter

---

snap-engine-utilities/src/main/java/org/esa/snap/engine_utilities/gpf/OperatorUtils.java

Include the causing exception on the thrown exception.
This seems like the smallest change to resolve #95  much else starts to need changes at the call sites.

FIX-95 Include causing exception in thrown exception

---

README.md

Missing protocol off the front of the ESA link at the top of the readme. This adds it so the link works.

Fix ESA url in readme

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/main/CommandLineContext.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/main/CommandLineTool.java

Should fix #107
Make enough bits public to be able to call it from another java application.

make gpf commandline public

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/AggregatedOpImage.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/DoubleDataAggregator.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/Resample.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/ResampleUtils.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/ResamplingOp.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/common/resample/AggregatedOpImageTest.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/common/resample/ResampleUtilsTest.java

This is not only a fix for SNAP-1060 ( https://senbox.atlassian.net/browse/SNAP-1060 ), but it also includes 
- a fix for setting no-data-values during aggregation
- a check whether all grids align at the corner or the center of the upper left pixel. This is considered during resampling, so the relationship between grids is preserved and unnecessary re-computations of existing grids are prevented
- the change that the determination whether to sample up or down is not made based on image dimensions but on base of image resolution

Snap 1060 downsampling fails

---

ceres-ui/src/main/java/com/bc/ceres/swing/binding/PropertyPane.java

This adds a method to get the PropertyPane return panel as a JScrollPanel instead of a JPanel.  This is important as some of the future tools modifications such as Graticule and Color Bar Layer contain too many parameters to fit in a standard non-scrolling window.

SEADAS-001a (PropertyPane: use JScrollPanel instead of JPanel)

---

snap-python/src/main/resources/snappy/snappyutil.py

I came across this error when trying to install snappy on my laptop.

fix AttributeError: 'list' object has no attribute 'join'

---

snap-core/src/main/java/org/esa/snap/core/util/ProductUtils.java

Added copying flagBands to the ProductUtils.copyProductNodes method.

---

ceres-core/src/main/java/com/bc/ceres/nbmgen/NbCodeGenTool.java
snap-binning/src/main/java/org/esa/snap/binning/operator/BinningOp.java
snap-collocation/src/main/java/org/esa/snap/collocation/CollocateOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/MosaicOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/SubsetOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/reproject/ReprojectionOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/resample/ResamplingOp.java

I am trying to uniform the Graph Builder menus with the main window menus, to do so the category in the operator descriptor must be the same as the one in the main menu.

Fixing category discrepancies

---

pom.xml
snap-core/src/main/java/org/esa/snap/core/datamodel/FXYGeoCoding.java
snap-core/src/main/java/org/esa/snap/core/datamodel/GeoPos.java
snap-core/src/main/java/org/esa/snap/core/datamodel/PixelGeoCoding.java
snap-core/src/main/java/org/esa/snap/core/datamodel/PixelGeoCoding2.java
snap-core/src/test/java/org/esa/snap/core/util/GeoUtilsTest.java

Defines that the maximum pixel position in width and the maximum pixel position in height, as well as 0 in x and y pixel position, is a valid part of the product.
With these changes, tie point based geo-coding or other pixel-based geo-codings behave the same way like math based geo-codings such as UTM.
This harmonized behavior is necessary to calculate valid envelopes for product reprojection with geotools.

Snap 999 geocoding border

---

snap-core/src/main/java/org/esa/snap/core/dataio/dimap/DimapHeaderWriter.java

The cast should be done without instance check. Otherwise we do not recognize changes in CrsGeocoding#getImageToMapTransform() which currenty allways returns an AffineTransform.
In the case we leave the code as it is, the CrsGeocoding can be changed without consequences. In such a case we allways write a new Double[6] array with 6 x 0.
Aso we should talk about the inserted todo.

Write image to map matrix

---

snap-core/src/main/java/org/esa/snap/core/dataop/dem/BaseElevationModel.java

synchronising access to the cache
Maybe it is also possible to remove the cache at all and deprecated the updateCache method and leave the implementation empty. I'm not sure if the tiles in the cache are the same which are used by elevationFiles.

[SNAP-1246] IndexOutOfBoundsException in BaseElevationModel

---

snap-core/src/main/java/org/esa/snap/core/image/AbstractMatrixMosaicSubsetMultiLevelSource.java
snap-core/src/main/java/org/esa/snap/core/image/AbstractMosaicSubsetMultiLevelSource.java
snap-core/src/main/java/org/esa/snap/core/util/ImageUtils.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffImageReader.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffMatrixCell.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffMatrixMultiLevelSource.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffMultiLevelSource.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffProductReader.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffRasterRegion.java
snap-geotiff/src/main/java/org/esa/snap/dataio/geotiff/GeoTiffTileOpImage.java

The new changes are used by readers from s2tbx (worldView, EsaWorldView, Spot Multi-Volume) which contain a matrix of tiff images for each band.
For these readers the image stream is opened when showing the band image in the UI to avoid memory exception in the TIFFImageReader.
In this case when loading the product from the disk the image streams are closed after reading the initialization data.

Geotiff reader corrections to open the stream to the tiff image later

---

snap-core/src/main/java/org/esa/snap/core/image/AbstractSubsetTileOpImage.java

Update lib-gdal for:
- eliminate dependencies between modules which uses GDAL Reader/Writer and lib-gdal module, by ensuring that GDAL libraries was initialized before using any GDAL Reader/Writer.
- report warning when unable to delete old GDAL drivers, instead of reporting error.
- fix issue with wrong name for method getIndexColorModel from ColorTable class driver.
- update solution with fetching process output for checking GDAL version command, by timing the process run time for prevent locking out SNAP when the process not responding.
Update GDAL Reader for:
- fix issues with reading GDAL products using blocks instead of rasters (issues with reading subsets not fully fixed at this time - temporary skip some tests).

GDAL reader: optimisation for reading using blocks

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/common/ReadOp.java

When running the ReadOp operator the copyMetadata attribute value must be true to copy by default
the metadata in the product readers.

Set by default the copyMetadata value with true to copy the metadata

---

snap-classification/src/main/java/org/esa/snap/classification/gpf/BaseClassifier.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/SupervisedClassifier.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/kdtknn/KDTreeKNNClassifierOp.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/knn/KNNClassifierOp.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/maximumlikelihood/MaximumLikelihoodClassifierOp.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/minimumdistance/MinimumDistanceClassifierOp.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/randomForest/RandomForestClassifierOp.java
snap-classification/src/main/java/org/esa/snap/classification/gpf/svm/SVMClassifierOp.java

The operators from snap-classification relied on that all vector data nodes are present at the time of initialize to set an index coding. This is not necessarily the case. In this PR, the index coding of the target product is created during doExecute.

classifier ops use doexecute

---

ceres-jai/pom.xml
snap-remote-products-repository/pom.xml

I got this error when running a build s2tbx-commons.
[INFO] Private classes referenced in module: [javax.xml.bind.ValidationEventHandler, javax.xml.bind.JAXBIntrospector, javax.xml.bind.annotation.XmlSeeAlso, javax.xml.bind.PropertyException, javax.xml.bind.attachment.AttachmentMarshaller, 
... 
javax.xml.bind.annotation.XmlElement, javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter]
[ERROR] Project depends on packages not accessible at runtime in module org.esa.snap:ceres-jai:jar:8.0.0-SNAPSHOT
With the changes in this PR it seems to be fixed.

Export xml bind

---

lib-openjpeg/pom.xml
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/CodestreamIndex.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/CodestreamInfo2.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/CompressionCodec.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/CompressionHandler.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/CompressionParams.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/DecompressCoreParams.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/DecompressParams.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/DecompressionCodec.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/DecompressionHandler.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/Image.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/ImageComponent.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/ImageComponentParams.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/MarkerInfo.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/PacketInfo.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/PoC.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/Precision.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/SegmentedFileInfo.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/Stream.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/TCCPInfo.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/TPIndex.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/TileIndex.java
lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/struct/TileInfo2.java
pom.xml
snap-netcdf/pom.xml

The OpenJpeg Module still used an old version of the jna library. This caused classloading issues when using gpt on the command line because interfaces have changed. So I updated the version and updated some classes because of the interface change.
Would be great if you could quickly review.

using version 5.5.0 of jna library

---

snap-gpf/src/main/java/org/esa/snap/core/gpf/main/CommandLineTool.java

For graphs created in the graphbuilder that already contain a write node, when processed by gpt an extra write node is inserted.
If a write node already exists then don't insert a new one.

If a write node already exists don't add a new write node

---

pom.xml
snap-cluster-analysis/pom.xml
snap-cluster-analysis/src/main/java/org/esa/snap/cluster/PrincipalComponentAnalysis.java
snap-core/pom.xml

To avoid conflicts with ejml dependencies. All code previously using efficient-java-matrix-library can migrate to org.ejml which is the currently maintained library.

migrate to org.ejml

---

pom.xml
snap-cluster-analysis/pom.xml
snap-core/pom.xml
snap-gpf/src/main/java/org/esa/snap/core/gpf/Operator.java

This should remove ejml library v0.34 from the classpath which is pulled in as transitive dependency from gt-referencing.
There is also a PR for s1tbx.
Luis, can you try if this still works for s1tbx?

remove ejml v0.34 from classpath

---

snap-core/src/main/java/org/esa/snap/dataio/ImageRegistryUtils.java

registerServiceProvider is not thread safe and throws if multiple GeoTiff readers are created at the same time.
synchronize registerImageInputStreamSpi
imageInputStreamSpi is never assigned

registerServiceProvider not thread safe

---

snap-dem/src/test/java/org/esa/snap/dem/dataio/copernicus/TestDownload.java

Using a system independent way of creating a temporary directory.
On my system the directory "/tmp" or c:\tmp does not exist.

Fixed IO Error in test 'TestDownload'

---

snap-raster/src/main/java/org/esa/snap/raster/gpf/masks/CreateLandMaskOp.java

Add multi-size source product exception in case of operator is used without the UI.
For the desktop UI, other exception appear during selection of a multi-size source product.

SNAP 1057 multi-size product exception

---

snap-remote-products-repository/pom.xml
snap-remote-products-repository/src/main/java/org/esa/snap/remote/products/repository/download/DownloadProductStatusListener.java

Update TAO version after fix issue with downloading S2 products from AWS remote repository.
JIRA: [SNAP-1405](https://senbox.atlassian.net/browse/SNAP-1405)

SNAP-1405: download s2 from aws fix

---

snap-core/src/main/java/org/esa/snap/core/datamodel/TransectProfileData.java
snap-core/src/main/java/org/esa/snap/core/datamodel/TransectProfileDataBuilder.java
snap-core/src/test/java/org/esa/snap/core/datamodel/TransectProfileDataBuilderTest.java

The “Invalid Pixel“ was inserted into the export because the pixel under the current mouse position was checked accidentally. If the cursor was at an invalid position, then the “Invalid Pixel“ was written and not the value.
Also did some refactorings.

[SNAP-1183] Export of transect pixels does not show correct values

---

.gitlab-ci.yml
pom.xml

Add first version of `.gitlab-ci.yaml` file.
Relative gitlab-ci project is [here](https://gitlab.com/senbox-org/snap-engine)
At the moment a runner will just pull the code and build the project.
More will come asap

[SCM-141] Add gitlab-ci.yaml to build & run UT on new CI platform

---

.gitlab-ci.yml

We were using to-be-continuous for convinience & best practices respect but there was an issue for SonarQube

[SCM-141]: Turn to custom file instead of to-be-continuous

---

.gitlab-ci.yml

Commit status is now well updated as pending when pipeline has started but not finished, success on success and failure on failure

[SCM-141] Fix report status

---

.gitlab-ci.yml

Deactivate unit tests when build for installer for the moment in order to get installer built anyway.

[SCM-141] Special flow when build installer

---

lib-gdal/src/main/java/org/esa/snap/dataio/gdal/GDALVersion.java

Fix for [SNAP-3488](https://senbox.atlassian.net/browse/SNAP-3488).
The error occurs only on the first startup of SNAP after installing the updates, because the internal distribution of GDAL is detected as installed version, and it gets replaced by the JNI driver which fails at loading time.
[SNAP-3488]: https://senbox.atlassian.net/browse/SNAP-3488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3488_lib-gdal_fix

---

lib-openjpeg/src/main/java/org/esa/snap/lib/openjpeg/dataio/OpenJP2Decoder.java

It is not available in JDK 11 anymore.
Replaced by `Raster.createWritableRaster(sampleModel, buffer, point);`
Please check if reading jp2files is still working as expected.
It tried and everything seems to work. But the line in question wasn't executed. Perhaps this is special case I'm not aware of.
Please merge and delete branch if you think this is okay.

removed the usage of sun.awt.image.SunWritableRaster. 

---

ceres-jai/pom.xml
pom.xml
snap-core/pom.xml
snap-remote-products-repository/pom.xml

Please note that I had to exclude imageio-ext-cog-reader, it is not compatible with the 1.1.3 version. So, no COG support with Imageio/JAI.
Please test supported data formats with special focus on GeoTiff.
* using jai-core-openjdk:1.1.4 and jai-codec-openjdk:1.1.4
* excluded jai_core:1.1.3 and jai_codec:1.1.3 from transitive dependencies
* had to remove imageio-ext-cog-reader too because it is not compatible with the old 1.1.3 libs
* excluded transitive dependencies to geotools modules from tao, pulled in old geotools version
* removed sun-image-classes dependency; not needed when using our jai-core-openjdk dependency

fixed dependency issues with imageio/jai

---

lib-gdal/src/test/java/org/esa/snap/dataio/gdal/OSCategoryTest.java

On some Unix systems `ping` is not available but `sh` should always be here

Fix GDAL library detection Unix

---

ceres-binding/src/main/java/com/bc/ceres/binding/ConverterRegistry.java
ceres-binding/src/main/java/com/bc/ceres/binding/converters/PathConverter.java
ceres-binding/src/test/java/com/bc/ceres/binding/converters/PathConverterTest.java
ceres-ui/src/main/java/com/bc/ceres/swing/binding/internal/PathEditor.java
ceres-ui/src/main/resources/META-INF/services/com.bc.ceres.swing.binding.PropertyEditor
ceres-ui/src/test/java/com/bc/ceres/swing/binding/internal/PathEditorTest.java

I've added a converter and editor for Path objects. Both are like their File counterparts.
Tests are included. It should be a step away from the old file API.

Support for paths as operator parameters and in GUI

---

snap-bigtiff/src/test/java/org/esa/snap/dataio/bigtiff/BigGeoTiffWriterTest.java
snap-core/src/main/java/org/esa/snap/core/datamodel/Product.java
snap-core/src/main/java/org/esa/snap/core/datamodel/ProductNode.java

The check that didn't allow the name of the product to be identical to the name of a band was removed

[SNAP-3631] Removed product name check

---

pom.xml
snap-stac/pom.xml

Updated to a single Mockito version property across modules. Replaced mockito-inline with mockito-core dependency for consistency.

Switch to unified Mockito version property

---

snap-core/src/main/java/org/esa/snap/core/dataio/AbstractProductBuilder.java
snap-core/src/main/java/org/esa/snap/core/dataio/ProductSubsetDef.java
snap-core/src/test/java/org/esa/snap/core/dataio/ProductSubsetDefTest.java

When subsetting multi-size products with bands that have non-overlapping regions, the regions rectangle for such bands is empty. Therefore, these bands are excluded from the subset

SNAP-3758, error when subsetting sentinel-1 products

---

snap-core/src/main/java/org/esa/snap/core/dataio/ProductIO.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/common/WriteOp.java
snap-gpf/src/main/java/org/esa/snap/core/gpf/internal/OperatorExecutor.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/execution/OperatorExecutionsTest.java
snap-gpf/src/test/java/org/esa/snap/core/gpf/internal/OperatorExecutorTest.java

Hello!
This is the 4th PR in a series of pull-requests. The aim is to improve processing performance by enhancing cache handling and the sequence in which tiles are processed.
In this PR, the OperatorExecutor directly iterates over images instead of using OperatorTileStackComputationListener and calling getTile() which is blocking and prevented parallelization. Also, updated and simplified tests. Expected results are now better traceable.
ProductIO now iterates first over the tiles and then over the bands. Before it was the other way around. In case of a tile-stack operator all images of the stack had to be in cache. Now only one tile-stack needs to be kept by the cache.
WriteOp - calling TileCache.memoryControl() instead of TileCache.flush(). Flush() tries to clear the whole cache. …

Enhanced gpf write and product io

---

snap-core/src/main/java/org/esa/snap/core/util/ImageUtils.java

There is related PR in the optical toolbox.
In Sentinel2L1BProductReader and Sentinel2OrthoProductReader ImageLayouts were created which didn’t match the image. In ImageUtils arbitrary models are created. Now, I’ve added a method to ImageUtils, which considers the SampleModel and ColorModel of an existing image.
This fixed the exception:
java.lang.IllegalArgumentException: The specified ColorModel is incompatible with the image SampleModel.
at javax.media.jai.PlanarImage.setImageLayout(Unknown Source)
at javax.media.jai.PlanarImage.<init>(Unknown Source)
at javax.media.jai.OpImage.<init>(Unknown Source)
at javax.media.jai.SourcelessOpImage.<init>(Unknown Source)
at com.bc.ceres.glevel.MultiLevelImage.<init>(MultiLevelImage.java:42)
at …

fix: ColorModel is incompatible with the image SampleModel

---

snap-dem/src/main/java/org/esa/snap/dem/gpf/ComputeSlopeAspectOp.java
snap-dem/src/test/java/org/esa/snap/gpf/ComputeSlopeAspectOpTest.java

The current Compute Slope and Aspect operator fails when pixel spacing is missing from the product metadata. The problem has been fixed by computing the pixel spacing using the geo-position information for pixels at the center of the image in case the pixel spacing is missing from the metadata.

Modified to estimate XY pixel spacing from pixel geo-position

---

snap-core/pom.xml

Moved commons-io dependency from opttbx-s2msi-reader to snap-core to centralize its usage. This ensures consistent versioning across modules and avoids redundancy.
see also: https://forum.step.esa.int/t/commons-io-dependency-issue-in-s2msi-reader/44516
This should resolve the issue when a module depends on s2msi-reader, snap-core and commons-io. In this case the module does not know where to load the classes from.  
`java.lang.ClassNotFoundException: Will not load class org.apache.commons.io.input.ReversedLinesFileReader arbitrarily from one of ModuleCL@4bc08f13[eu.esa.opt.opttbx.s2msi.reader] and ModuleCL@29091e7a[org.esa.snap.snap.core] starting from ModuleCL@e56c0cf[org.eomasters.eomtbx]`
There is a related pull request for the opttbx …

S2reader commons-io dependency issue
